config/routes.rb
Timecard::Application.routes.draw do
  resource :dashboard, only: :show
  devise_for :users, controllers:  { omniauth_callbacks: "users/omniauth_callbacks", registrations: 'users/registrations' }
  resources :users, only: [:show] do
    resources :workloads, only: [:index] do
      get '/:year/:month/:day', on: :collection, to: 'workloads#index', as: :daily
    end
    resources :authentications
    resources :reports, only: :index
  end

  resources :members, only: [:update, :destroy]
  resources :data

  resources :comments, only: [:edit, :update, :destroy]
  resources :workloads, only: [:edit, :update, :destroy, :stop] do
    patch :stop, on: :member
  end

  resources :issues, only: [:index, :show, :edit, :update, :close, :reopen] do
    patch :close, on: :member
    patch :reopen, on: :member
    patch :postpone, on: :member
    patch :do_today, on: :member
    resources :comments, only: [:create]
    resource :workloads, only: :create
  end

  resources :projects do
    patch :active, on: :member
    patch :close, on: :member
    resources :issues, only: [:index, :new, :create]
    resources :members, only: [:index, :create] do
      collection do
        get :search
      end
    end
    resources :crowdworks_contracts, only: [:new, :create]
    resources :reports, only: :index
    resources :github_imports, only: :create
  end

  resources :crowdworks_contracts, only: [:edit, :update, :destroy]

  resources :reports, only: :index

  delete "users/disconnect/:provider", to: "users#disconnect", as: :disconnect_provider
  root :to => "home#index"
  mount API => "/"
end

app/models/issue.rb
class Issue < ActiveRecord::Base
  include PublicActivity::Model

  default_scope { order("updated_at DESC") }

  scope :open, -> { where("status = ?", 1) }
  scope :closed, -> { where("status = ?", 9) }
  scope :do_today, -> { open.where("will_start_at is null OR will_start_at < ?", Time.now) }
  scope :not_do_today, -> { open.where("will_start_at >= ?", Time.now) }
  scope :with_status, ->(status = "open") do
    status = "open" if status.blank?
    case status
    when "open"
      do_today
    when "closed"
      closed
    when "not_do_today"
      not_do_today
    end
  end

  attr_accessor :labels, :continue, :enabled_github

  belongs_to :project
  belongs_to :author, class_name: "User", foreign_key: :author_id
  belongs_to :assignee, class_name: "User", foreign_key: :assignee_id
  has_one :github, ->{ where(name: "github", provided_type: "Issue") }, foreign_key: :foreign_id, class_name: "IssueGithub"
  has_one :ruffnote, ->{ where(name: "ruffnote", provided_type: "Issue") }, foreign_key: :foreign_id, class_name: "IssueRuffnote"

  has_many :comments
  has_many :workloads

  validates :subject, presence: true

  before_create :create_github_issue
  after_create :track_create_activity
  before_update :track_update_status_activity, :update_github_issue

  def add_github(issue)
    issue_github = build_github
    issue_github.number = issue.number
    issue_github.html_url = issue.html_url
    issue_github.labels = issue.labels
    issue_github.save
  end

  def edit_github(issue)
    issue_github = github
    issue_github.number = issue.number
    issue_github.html_url = issue.html_url
    issue_github.labels = issue.labels
    issue_github.save
  end

  def add_ruffnote(number) #index
    issue_ruffnote = IssueRuffnote.find_or_create_by(
      name: "ruffnote",
      provided_type: "Issue",
      foreign_id: self.id
    )
    issue_ruffnote.number = number
    full_name = self.project.ruffnote.full_name
    issue_ruffnote.html_url = "#{Settings.services.ruffnote.url}/#{full_name}/issues/#{number}"
    issue_ruffnote.save
  end

  def provider
    return github if github
    return ruffnote if ruffnote
    nil
  end

  def toggle_status
    closed? ? reopen : close
  end

  def close
    update(status: 9, closed_on: Time.now.utc)
  end

  def reopen
    update(status: 1)
  end

  def do_today?
    return true if self.will_start_at.nil? || self.will_start_at < Time.now
    false
  end

  def closed?
    status == 9 ? true : false
  end

  def github_labels
    return [] if github.blank?
    return [] if github.labels.blank?
    github.labels
  end

  def time_tracker
    workloads.complete.map { |wk| wk.user }
  end

  private

  def track_create_activity
    self.create_activity(:create, owner: self.author, recipient: self.project)
  end

  def track_update_status_activity
    if self.changes.has_key?("status")
      if self.changes["status"][1] == 1
        self.create_activity(:reopen, owner: User.current, recipient: self.project)
      else
        self.create_activity(:close, owner: User.current, recipient: self.project)
      end
    end
  end

  def state_of_github
    case status
    when 1
      "open"
    when 9
      "close"
    end
  end

  def create_github_issue
    if enabled_github
      owner, repo = project.github.full_name.split("/")
      client = Github.new(oauth_token: author.github.oauth_token)
      issue = client.issues.create(
        owner, repo, github_options
      )
      add_github(issue)
    end
  rescue Github::Error::GithubError => e
    if e.is_a? Github::Error::ServiceError
      errors.add(:base, e.body)
    elsif e.is_a? Github::Error::ClientError
      errors.add(:base, e.message)
    end
    false
  end

  def update_github_issue
    if github
      owner, repo = project.github.full_name.split("/")
      client = Github.new(oauth_token: author.github.oauth_token)
      issue = client.issues.edit(
        owner, repo, github.number, github_options
      )
      edit_github(issue)
    end
    if enabled_github
      create_github_issue
    end
  rescue Github::Error::GithubError => e
    if e.is_a? Github::Error::ServiceError
      errors.add(:base, e.body)
    elsif e.is_a? Github::Error::ClientError
      errors.add(:base, e.message)
    end
    false
  end

  def github_options
    options = {}
    options["title"] = subject.presence
    options["body"] = description.presence
    options["state"] = state_of_github
    options["author"] = author.name
    options["assignee"] = assignee.try(:name)
    options["labels"] = labels
    options
  end
end

app/controllers/issues_controller.rb
class IssuesController < ApplicationController
  load_and_authorize_resource :project, only: [:index, :new, :create]
  load_and_authorize_resource :issue, except: [:index, :new, :create]
  before_action :load_members, except: [:index, :show, :destroy]
  before_action :load_labels, except: [:index, :show, :destroy]

  def index
    if params[:user_id].present?
      @issues = @project.issues
      .with_status(params[:status])
      .where("assignee_id = ?", params[:user_id])
      .page(params[:page])
      .per(params[:per_page])
    else
      @issues = @project.issues
      .with_status(params[:status])
      .includes(:github, :ruffnote, :comments)
      .page(params[:page])
      .per(params[:per_page])
    end

    respond_to do |format|
      format.json
    end
  end

  def show
  end

  def new
    @issue = @project.issues.build
    authorize! :create, @issue
  end

  def edit
  end

  def create
    @issue = @project.issues.build(issue_params)
    authorize! :create, @issue
    respond_to do |format|
      if @issue.save
        if Authentication.exists?(["provider = 'chatwork'"])
          rails_host = env["HTTP_HOST"]
          body = "#{current_user.name}さんが「#{@issue.project.name}」に「#{@issue.subject}」を追加しました\nhttp://#{rails_host}/issues/#{@issue.id}"
          Chatwork.post(body)
        end

        if @issue.project.ruffnote && current_user.ruffnote
          issue = @issue.project.ruffnote.add_issue(current_user.ruffnote.oauth_token , params[:issue])
          if issue
            @issue.add_ruffnote(issue['index'])
          else
            flash[:alert] = 'Create a new issue to Ruffnote failed.' + @issue.errors.full_messages.join("\n")
            format.html { render action: 'new' }
          end
        end

        if issue_params[:continue]
          format.html { redirect_to new_project_issue_path(@project), notice: "Issue was successfully created." }
        else
          format.html { redirect_to @issue, notice: "Issue was successfully created." }
        end
        format.json { render action: 'show', status: :created, location: @issue }
      else
        format.html { render action: 'new' }
        format.json { render json: @issue.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @issue.update(issue_params)
        if @issue.project.ruffnote && current_user.ruffnote
          issue = @issue.ruffnote.modify(
            current_user.ruffnote.oauth_token, issue_params
          )
          unless issue
            flash[:alert] = 'Update a new issue to Ruffnote failed.' + @issue.errors.full_messages.join("\n")
            format.html { render action: 'edit' }
          end
        end

        format.html { redirect_to @issue, notice: 'Issue was successfully updated.' }
        format.json { render action: "issue" }
      else
        format.html { render action: 'edit' }
        format.json { render json: @issue.errors, status: :unprocessable_entity }
      end
    end
  end

  def close
    current_user.stop_time_track

    if @issue.close
      if @issue.ruffnote
        @issue.ruffnote.close(current_user.ruffnote.oauth_token)
      end
      respond_to do |format|
        format.html { redirect_to @issue, notice: 'Issue was successfully updated.' }
        format.json { render action: "issue" }
      end
    end
  rescue Github::Error::GithubError => e
    if e.is_a? Github::Error::ServiceError
      @issue.errors.add(:base, e.body)
    elsif e.is_a? Github::Error::ClientError
      @issue.errors.add(:base, e.message)
    end
    redirect_to @issue
  end

  def reopen
    if @issue.reopen
      if @issue.ruffnote
        @issue.ruffnote.reopen(current_user.ruffnote.oauth_token)
      end
      respond_to do |format|
        format.html { redirect_to @issue, notice: 'Issue was successfully updated.' }
        format.json { render action: "issue" }
      end
    end
  rescue Github::Error::GithubError => e
    if e.is_a? Github::Error::ServiceError
      @issue.errors.add(:base, e.body)
    elsif e.is_a? Github::Error::ClientError
      @issue.errors.add(:base, e.message)
    end
    redirect_to @issue
  end

  def postpone
    if @issue.update(will_start_at: 1.day.since(Time.now.utc))
      respond_to do |format|
        format.html { redirect_to @issue, notice: 'Issue was successfully updated.' }
        format.json { render action: "issue" }
      end
    end
  end

  def do_today
    if @issue.update(will_start_at: Time.now.utc)
      respond_to do |format|
        format.html { redirect_to @issue, notice: 'Issue was successfully updated.' }
        format.json { render action: "issue" }
      end
    end
  end

  private

  def issue_params
    params.require(:issue).permit(:subject, :description, :author_id, :assignee_id, :will_start_at, :status, :continue, :enabled_github, labels: [])
  end

  def load_members
    if params[:project_id]
      # new, create
      if @project.github
        @members = @project.github_members(current_user.github.oauth_token)
      else
        @members = @project.members
      end
    else
      # edit, update
      if @issue.github
        @members = @issue.project.github_members(current_user.github.oauth_token)
      else
        @members = @issue.project.members
      end
    end
  end

  def load_labels
    if params[:project_id]
      # new, create
      if @project.github
        github = Github.new(token: current_user.github.oauth_token)
        owner, repo = @project.github_full_name.split("/")
        @labels = github.issues.labels.list(user: owner, repo: repo)
      end
    else
      # edit, update
      if @issue.github
        github = Github.new(token: current_user.github.oauth_token)
        owner, repo = @issue.project.github_full_name.split("/")
        @labels = github.issues.labels.list(user: owner, repo: repo)
      end
    end
  end
end

app/views/issues/_actions.html.haml
.issue__actions
  - if @issue.status == 1
    = link_to "Close", close_issue_path(@issue), class: "btn btn-danger", data: { confirm: "Are you sure?" }, method: :patch
  - else
    = link_to "Reopen", reopen_issue_path(@issue), class: "btn btn-default", method: :patch
  - if @issue.will_start_at.present? && @issue.will_start_at >= Time.now.utc
    = link_to "Do today", do_today_issue_path(issue_id: @issue), class: "btn btn-default", method: :patch
  - else
    = link_to "Don't do today", postpone_issue_path(issue_id: @issue), class: "btn btn-default", method: :patch
  .time-entries__buttons
    %span{ class: "time-entries__start-button #{current_user.time_tracking?(@issue) ? 'hidden' : ''}" }
      = link_to "#", class: "btn btn-primary" do
        = fa_icon "play"
        START
    %span{ class: "time-entries__stop-button #{current_user.time_tracking?(@issue) ? '' : 'hidden'}" }
      = link_to "#", class: "btn btn-warning" do
        = fa_icon "pause"
        STOP

app/views/issues/_issue.html.haml
= div_for issue, class: "media" do
  .pull-left
    .issue-subject
      %b
        = link_to_provider(issue)
        = link_to issue.subject, issue
    .issue-author
      Opend by #{link_to issue.author.name, issue.author} #{time_ago_in_words(issue.created_at)} ago
    .issue-asignee
      - if issue.assignee
        Assigned to #{link_to issue.assignee.name, issue.assignee}
    .issue-status
      - if issue.status == 1
        %span.label.label-success Open
      - else
        %span.label.label-danger Closed
  - if can? :update, issue
    .actions.pull-right
      - if issue.status == 1
        = link_to "Close", close_issue_path(issue, format: :json), remote: true, method: :patch, class: "btn btn-danger js-hide-issue"
      - else
        = link_to "Reopen", reopen_issue_path(issue, format: :json), remote: true, method: :patch, class: "btn btn-default js-hide-issue"
      - if issue.status == 1
        - if issue.do_today?
          = link_to "Don't do today", postpone_issue_path(issue, format: :json), remote: true, method: :patch, class: "btn btn-default js-hide-issue"
        - else
          = link_to "Do today", do_today_issue_path(issue, format: :json), remote: true, method: :patch, class: "btn btn-default js-hide-issue"
        - if current_user.time_tracking?(issue)
          = link_to "Stop", stop_workload_path(current_user.current_entry), remote: true, method: :patch, class: "btn btn-warning js-stop-workload-button"
        - else
          = link_to "Start", issue_workloads_path(issue_id: issue.id), remote: true, method: :post, class: "btn btn-primary js-start-workload-button"

app/views/issues/edit.html.haml
.row
  .col-sm-offset-2.col-sm-8.col-md-offset-2.col-md-8.issue-form
    .issue__back
      = link_to @issue.project, class: "issue__back__link" do
        = fa_icon "chevron-left"
      = @issue.project.name
    %hr
    = form_for @issue, data: { "project-id" => @issue.project.id } do |f|
      - if @issue.errors.any?
        #error_explanationpnnel.panel.panel-danger
          .panel-heading
            #h2= "#{pluralize(@issue.errors.count, "error")} prohibited this issue from being saved:"

          .panel-body
            %ul
            - @issue.errors.full_messages.each do |msg|
              %li= msg
      = f.hidden_field :author_id, value: @issue.author.id
      .form-group
        = f.text_field :subject, class: "form-control", placeholder: "Subject"
      .form-group
        %ul.nav.nav-tabs{ role: "tablist" }
          %li.active
            = link_to "Write", ".issue__description--write", role: "tab", "data-toggle" => "tab"
          %li
            = link_to "Preview", ".issue__description--preview", role: "tab", "data-toggle" => "tab", class: "issue__preview-button"
        .tab-content
          .tab-pane.active.issue__description--write
            = f.text_area :description, class: "form-control", placeholder: "Leave a comment", rows: "5"
          .tab-pane.issue__description--preview.markdown-body
            %p
              Loading content ...
      .form-group
        #js-assignee-select-box
          = f.select :assignee_id, @members.collect { |m| [ "#{m.user.name} will be assigned", m.user.id ] }, { include_blank: true }, class: "form-control"
      - if current_user.github && @issue.github
        .form-group
          %ul.issue__labels
            - @labels.each_with_index do |github_label, index|
              %li.issue__labels__item
                .checkbox
                  = label_tag nil do
                    = check_box_tag "issue[labels][]", github_label.name, @issue.github_labels.any? { |label| label["name"] == github_label.name }
                    %span.label{ style: calc_label_color(github_label.color) }
                      = github_label.name
      - if @issue.will_start_at.blank?
        .form-group
          .issue__will-start-at__link--add
            = link_to "When will you start this issue?", "#", class: "js-add-will-start-at"
          .hidden.issue__will-start-at__field
            .form-datetime-select
              = f.datetime_select :will_start_at, {}, class: "form-control", disabled: true
              %button.close.issue__will-start-at__link--close{ type: "button", aria: { hidden: "true" } } &times;
      - else
        .form-group#will-start-at
          = f.label :will_start_at
          %br
          = f.datetime_select :will_start_at, {}, class: "form-control"
      - if current_user.github && @issue.project.github && @issue.github.blank?
        %hr
        .form-group.checkbox
          = label_tag "github" do
            = check_box_tag "issue[enabled_github]", 1, @issue.github, checked: !@issue.github.blank?, id: "js-add-github-checkbox"
          Github
          %br
          %span.text-muted If checked add this issue to github.
      %hr
      .actions.pull-right
        = f.submit "Update", class: "btn btn-success"

app/views/issues/new.html.haml
.row
  .col-sm-offset-2.col-sm-8.col-md-offset-2.col-md-8.issue-form
    .issue__back
      = link_to @project, class: "issue__back__link" do
        = fa_icon "chevron-left"
      = @project.name
    %hr
    = form_for [@project, @issue], data: { "project-id" => @project.id } do |f|
      - if @issue.errors.any?
        #error_explanation.panel.panel-danger
          .panel-heading
            %h3.panel-title= "#{pluralize(@issue.errors.count, "error")} prohibited this issue from being saved:"
          .panel-body
            %ul
              - @issue.errors.full_messages.each do |msg|
                %li= msg
      = f.hidden_field :author_id, value: current_user.id
      .form-group
        = f.text_field :subject, class: "form-control", placeholder: "Subject"
      .form-group
        %ul.nav.nav-tabs{ role: "tablist" }
          %li.active
            = link_to "Write", ".issue__description--write", role: "tab", "data-toggle" => "tab"
          %li
            = link_to "Preview", ".issue__description--preview", role: "tab", "data-toggle" => "tab", class: "issue__preview-button"
        .tab-content
          .tab-pane.active.issue__description--write
            = f.text_area :description, class: "form-control", placeholder: "Leave a comment", rows: "5"
          .tab-pane.issue__description--preview.markdown-body
            %p
              Loading content ...
      .form-group
        #js-assignee-select-box
          = f.select :assignee_id, @members.collect { |m| [ "#{m.user.name} will be assigned", m.user.id ] }, { selected: current_user.id, include_blank: true }, class: "form-control"

      - if current_user.github && @issue.project.github
        .form-group
          %ul.issue__labels
            - @labels.each_with_index do |github_label, index|
              %li.issue__labels__item
                .checkbox
                  = label_tag nil do
                    = check_box_tag "issue[labels][]", github_label.name, false
                    %span.label{ style: calc_label_color(github_label.color) }
                      = github_label.name

      .form-group
        .issue__will-start-at__link--add
          = link_to "When will you start this issue?", "#", class: "js-add-will-start-at"
        .hidden.issue__will-start-at__field
          .form-datetime-select
            = f.datetime_select :will_start_at, {}, class: "form-control", disabled: true
            %button.close.issue__will-start-at__link--close{ type: "button", aria: { hidden: "true" } } &times;
      - if current_user.github && @issue.project.github
        %hr
        .form-group.checkbox
          = label_tag nil do
            = check_box_tag "issue[enabled_github]", 1, @issue.github, checked: true, id: "js-add-github-checkbox"
            Github
            %br
            %span.text-muted If checked add this issue to github.
      %hr
      .clearfix
        .pull-right
          = f.submit "Continue to create issue", class: "btn btn-primary issue__continue-button"
          = f.submit "Create a new issue", class: "btn btn-success"

app/views/issues/show.html.haml
= link_to @issue.project do
  = fa_icon "angle-double-left"
  = @issue.project.name
.row
  .col-lg-6
    %section.issue
      %h1.issue__subject
        = link_to_provider(@issue)
        = @issue.subject
      .issue__meta
        .issue__status
          - if @issue.status == 1
            %span.label.label-success
              = fa_icon "exclamation-circle"
              Open
          - else
            %span.label.label-danger
              = fa_icon "check-circle"
              Closed
        .issue__author.text-muted
          %b= link_to @issue.author.name, @issue.author
          opened this issue on #{@issue.created_at.to_date.to_s(:long)}
        - if can?(:update, @issue)
          = link_to "Edit", edit_issue_path(@issue)

        - if @issue.github && @issue.github.labels
          .issue__labels
            - @issue.github.labels.each do |github_label|
              %span.label.issue__label{ style: "background-color:##{github_label["color"]}" }
                = github_label["name"]

        .issue__assignee.text-muted
          - if @issue.assignee.present?
            = image_tag gravatar_url(@issue.assignee.email, 20)
            %b= link_to @issue.assignee.name, @issue.assignee
            is assigned
          - else
            No one is assigned
          will start at #{@issue.will_start_at || "today"}
      .issue__description
        = @issue.description.present? ? markdown(@issue.description) : "No description given."
      - if can?(:update, @issue)
        %hr
        = render 'actions'

      <!-- Modal -->
      .modal.fade.crowdworks-form__modal{ tabindex: "-1", role: "dialog", "aria-labelledby" => "myModalLabel", "aria-hidden" => "true" }
        .modal-dialog
          .modal-content
            .modal-header
              %button.close{ type: "button", "data-dismiss" => "modal" }
                %span{ "aria-hidden" => "true" } &times;
                %span.sr-only Close
              %h4.modal-title#myModalLabel
                CrowdWorks Password
            .modal-body
              %p Please input your crowdworks password.
              .form-group
                = password_field_tag :password, nil, class: "form-control crowdworks-form__password"
              .checkbox
                = label_tag nil do
                  = check_box_tag :remember_me, nil, false, class: "crowdworks-form__remember-me"
                  Remember me while browser open.
            .modal-footer
              %button.btn.btn-default{ type: "button", "data-dismiss" => "modal" }
                Cancel
              %button.btn.btn-primary.crowdworks-form__submit{ type: "button" }
                OK

    %section
      %ul.media-list.comment-list
        - @issue.comments.order("id ASC").each do |comment|
          = render "comments/list_item", comment: comment
      - if can?(:create, @issue)
        .comment-form
          = form_for [@issue, Comment.new] do |f|
            .form-group
              %ul.nav.nav-tabs{ role: "tablist" }
                %li.active
                  = link_to "Write", "#comment__body--write", role: "tab", "data-toggle" => "tab"
                %li
                  = link_to "Preview", "#comment__body--preview", role: "tab", "data-toggle" => "tab", class: "comment__preview-button"
              .tab-content
                .tab-pane.active#comment__body--write
                  = f.text_area :body, class: "form-control", placeholder: "Leave a comment", rows: "5"
                .tab-pane#comment__body--preview.markdown-body
            .actions.text-right
              - if @issue.closed?
                = button_tag "Reopen", class: "btn btn-default issue__reopen-and-comment-button issue__comment-and-button", "data-comment-text" => "Reopen and comment", "data-original-text" => "Reopen"
              - else
                = button_tag "Close", class: "btn btn-danger issue__close-and-comment-button issue__comment-and-button", "data-comment-text" => "Close and comment", "data-original-text" => "Close"
              = f.submit "Comment", class: "btn btn-success"

  .col-lg-6
    %section.time-entries
      .time-entries__head
        %h2
          = fa_icon "clock-o"
          Time Entries
          %small= @issue.workloads.formatted_total_duration
      .time-entries__overview
        .row
          .col-lg-12
            %h3.text-muted Overview of each user
          - @issue.time_tracker.uniq.each do |user|
            .col-lg-6
              .time-entries__user
                .pull-left
                  .time-entries__user__image
                    = image_tag gravatar_url(user.email, 32), class: "img-circle"
                .time-entries__user__name
                  = user.name
                .time-entries__user__total-duration.text-muted
                  = @issue.workloads.where(user: user).formatted_total_duration

      %ul.media-list.workload-list
        - @issue.workloads.complete.order("updated_at DESC").each do |workload|
          = render "workloads/list_item", workload: workload

:javascript
  $(function() {
    var issue = new Timecard.Models.Issue(JSON.parse("#{j(@issue.to_json)}"));
    var time_entries = new Timecard.Collections.Workloads(JSON.parse("#{j(@issue.workloads.where(user: current_user).order("updated_at DESC").to_json)}"));
    issue.isCrowdworks = #{current_user.authentications.exists?(["provider = ?", "crowdworks"]) && @issue.project.crowdworks_contracts.exists?(["user_id = ?", current_user.id])};
    var viewIssuesShow = new Timecard.Views.IssuesShow({
      model: issue,
      time_entries: time_entries
    }).render();
  });