config/routes.rb
Timecard::Application.routes.draw do
  resource :dashboard, only: :show
  devise_for :users, controllers:  { omniauth_callbacks: "users/omniauth_callbacks", registrations: 'users/registrations' }
  resources :users, only: [:show] do
    resources :workloads, only: [:index] do
      get '/:year/:month/:day', on: :collection, to: 'workloads#index', as: :daily
    end
    resources :authentications
    resources :reports, only: :index
  end

  resources :members, only: [:update, :destroy]
  resources :data

  resources :comments, only: [:edit, :update, :destroy]
  resources :workloads, only: [:edit, :update, :destroy, :stop] do
    patch :stop, on: :member
  end

  resources :issues, only: [:index, :show, :edit, :update, :close, :reopen] do
    patch :close, on: :member
    patch :reopen, on: :member
    patch :postpone, on: :member
    patch :do_today, on: :member
    resources :comments, only: [:create]
    resource :workloads, only: :create
  end

  resources :projects do
    patch :active, on: :member
    patch :close, on: :member
    resources :issues, only: [:index, :new, :create]
    resources :members, only: [:index, :create] do
      collection do
        get :search
      end
    end
    resources :crowdworks_contracts, only: [:new, :create]
    resources :reports, only: :index
    resources :github_imports, only: :create
  end

  resources :crowdworks_contracts, only: [:edit, :update, :destroy]

  resources :reports, only: :index

  delete "users/disconnect/:provider", to: "users#disconnect", as: :disconnect_provider
  root :to => "home#index"
  mount API => "/"
end

app/models/workload.rb
class Workload < ActiveRecord::Base
  include PublicActivity::Model

  default_scope { order("updated_at DESC") }

  scope :complete, -> { where("end_at is not ?", nil) }
  scope :uncomplete, -> { where("end_at IS NULL") }
  scope :daily, ->(now = Time.zone.now) do
    where("start_at >= ? AND start_at < ?", now.beginning_of_day, now.end_of_day) 
  end
  scope :weekly, ->(now = Time.zone.now) do
    where("start_at >= ? AND start_at <= ?", now.beginning_of_week, now.end_of_week)
  end

  belongs_to :issue
  belongs_to :user

  validates :start_at, presence: true

  after_create :track_start_activity
  before_update :track_stop_activity

  def self.running?
    exists?(["start_at is not ? and end_at is ?", nil, nil])
  end

  def duration
    end_at_or_now - start_at
  end

  def self.total_duration
    complete.inject(0) {|sum, w| sum += w.duration }
  end

  def self.formatted_total_duration
    duration = self.total_duration
    hour = (duration / (60 * 60)).floor
    duration = duration - (hour * 60 * 60)
    min = (duration / 60).floor
    sec = duration - (min * 60)
    "#{sprintf('%02d', hour)}:#{sprintf('%02d', min)}:#{sprintf('%02d', sec)}"
  end

  def formatted_duration(format = '%h:%m:%s')
    Time.diff(start_at, end_at_or_now, format)[:diff]
  end

  def formatted_distance_of_time
    started_at = "#{sprintf('%02d', start_at.hour)}:#{sprintf('%02d', start_at.min)}"
    stopped_at = "#{sprintf('%02d', end_at.hour)}:#{sprintf('%02d', end_at.min)}"
    "#{started_at}-#{stopped_at}"
  end

  def stop
    update!(end_at: Time.now)
  end

  private

  def track_start_activity
    self.create_activity(:start, owner: self.user, recipient: self.issue.project)
  end

  def track_stop_activity
    if self.changes.has_key?("end_at") && self.changes["end_at"][0] == nil
      self.create_activity(:stop, owner: self.user, recipient: self.issue.project)
    end
  end

  def end_at_or_now
    (end_at.presence || Time.zone.now)
  end
end

app/controllers/workloads_controller.rb
class WorkloadsController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource :workload, except: [:index, :create]

  rescue_from Crowdworks::Error::PasswordNotFound, with: :crowdworks_errors
  rescue_from Crowdworks::Error::LoginFailed, with: :crowdworks_errors

  def index
    if params[:user_id].present?
      if params[:day].present?
        date = Date.parse("#{params[:year]}-#{params[:month]}-#{params[:day]}")
        @workloads = current_user.workloads.daily(date).complete
      else
        @workloads = current_user.workloads.complete
      end
    end

    respond_to do |format|
      format.json
    end
  end

  def edit
  end

  def create
    @issue = Issue.find(params[:issue_id])
    @workload = current_user.start_time_track(@issue)

    if Authentication.exists?(["provider = 'chatwork'"])
      rails_host = env["HTTP_HOST"]
      body = "#{current_user.name}さんが「#{@issue.project.name}」における「#{@issue.subject}」を開始しました\nhttp://#{rails_host}/issues/#{@issue.id}"
      Chatwork.post(body)
    end

    render "workload"
  rescue => e
    render json: { errors: e.message }, status: :unprocessable_entity
  end

  def update
    respond_to do |format|
      if @workload.update(workload_params)
        if current_user.crowdworks && @workload.issue.project.crowdworks_contracts.exists?(["user_id = ?", current_user.id])
          logging_crowdworks
        end
        format.html { redirect_to @workload.issue, notice: 'Work log was successfully updated.' }
        format.json { render action: "workload" }
      else
        format.html { render action: 'edit' }
        format.json { render json: @workload.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @workload.destroy
    respond_to do |format|
      format.html { redirect_to @workload.issue }
      format.json { head :no_content }
    end
  end

  private

  def workload_params
    params.require(:workload).permit(:id, :start_at, :end_at, :issue_id, :user_id, :created_at, :updated_at, :password)
  end

  def logging_crowdworks
    @crowdworks = Crowdworks.new
    @crowdworks.login(current_user.crowdworks.username, params[:password])
    @crowdworks.submit_timesheet(@workload)
  end

  def crowdworks_errors
    render json: { workload: @workload.to_json, errors: @workload.errors }, status: :unprocessable_entity
  end
end

app/views/workloads/_form.html.haml
= form_for(@workload) do |f|
  - if @workload.errors.any?
    #error_explanation
      %h2
        = pluralize(@workload.errors.count, "error")
        prohibited this workload from being saved:
      %ul
        - @workload.errors.full_messages.each do |msg|
          %li= msg
  .form-group
    = f.label :start_at
    %br/
    = f.datetime_select :start_at
  .form-group
    = f.label :end_at
    %br/
    = f.datetime_select :end_at
  .actions
    = f.submit class: "btn btn-default"

app/views/workloads/_list_item.html.haml
%li.media.workload-list__item
  .pull-left
    = link_to workload.user do
      = image_tag gravatar_url(workload.user.email), class: "img-circle"
  .media-body
    .workload
      - if can? :destroy, workload
        = link_to workload, class: "close", data: { confirm: "Are you sure?" }, method: :delete do
          &times;
        - if can?(:update, workload)
          = link_to edit_workload_path(workload), class: "workload__edit-button pull-right", title: "Edit workload" do
            = fa_icon "pencil"
      .workload__duration
        = link_to workload.user.name, workload.user
        %span.text-muted
          worked #{workload.formatted_duration}
      .workload__time
        #{l(workload.start_at, format: :short)} - #{l(workload.end_at, format: :short)}

app/views/workloads/edit.html.haml
%h1 Editing workload
= render 'form'

app/views/workloads/start.js.haml
- if @prev_issue.present?
  $('#issue_#{@prev_issue.id}').html('#{j(render @prev_issue)}');
$('#issue_#{@issue.id}').html('#{j(render @issue)}');
$('#running-users').html('#{j(render partial: "shared/running_users")}');
var start_time = new Date(Date.parse('#{@workload.start_at.to_s(:rfc822)}'));
Workload.start(start_time);

app/views/workloads/stop.js.haml
$('#issue_#{@workload.issue_id}').html('#{j(render @workload.issue)}');