config/routes.rb
Timecard::Application.routes.draw do
  resource :dashboard, only: :show
  devise_for :users, controllers:  { omniauth_callbacks: "users/omniauth_callbacks", registrations: 'users/registrations' }
  resources :users, only: [:show] do
    resources :workloads, only: [:index] do
      get '/:year/:month/:day', on: :collection, to: 'workloads#index', as: :daily
    end
    resources :authentications
    resources :reports, only: :index
  end

  resources :members, only: [:update, :destroy]
  resources :data

  resources :comments, only: [:edit, :update, :destroy]
  resources :workloads, only: [:edit, :update, :destroy, :stop] do
    patch :stop, on: :member
  end

  resources :issues, only: [:index, :show, :edit, :update, :close, :reopen] do
    patch :close, on: :member
    patch :reopen, on: :member
    patch :postpone, on: :member
    patch :do_today, on: :member
    resources :comments, only: [:create]
    resource :workloads, only: :create
  end

  resources :projects do
    patch :active, on: :member
    patch :close, on: :member
    resources :issues, only: [:index, :new, :create]
    resources :members, only: [:index, :create] do
      collection do
        get :search
      end
    end
    resources :crowdworks_contracts, only: [:new, :create]
    resources :reports, only: :index
    resources :github_imports, only: :create
  end

  resources :crowdworks_contracts, only: [:edit, :update, :destroy]

  resources :reports, only: :index

  delete "users/disconnect/:provider", to: "users#disconnect", as: :disconnect_provider
  root :to => "home#index"
  mount API => "/"
end

app/models/project.rb
class Project < ActiveRecord::Base
  STATUS_ACTIVE   = 1
  STATUS_CLOSED   = 5

  scope :active, -> { where(status: STATUS_ACTIVE) }
  scope :closed, -> { where(status: STATUS_CLOSED) }
  scope :published, -> { where(is_public: true) }
  scope :visible, -> (user) { where(id: Member.where(user_id: user.id).pluck(:project_id)) }

  has_many :members, dependent: :destroy
  has_many :issues, dependent: :destroy
  has_many :crowdworks_contracts

  validates :name, presence: true

  def admin?(user)
    member?(user) ? members.find_by("user_id = ?", user.id).is_admin : false
  end

  def admin
    members.find_by(is_admin: true).user
  end

  def member?(user)
    members.exists?(["user_id = ?", user.id]) ? true : false
  end

  def providers
    Provider.where(
      provided_type: "Project",
      foreign_id: self.id
    ).map do |p|
      if p.name == "github"
        ProjectGithub.find(p.id) #FIXME
      end
    end
  end

  def update(params)
    if params[:github_full_name]
      if self.add_github(params[:github_full_name])
        params.delete(:github_full_name)
      else
        return false
      end
    end
    if params[:ruffnote_full_name]
      self.add_ruffnote(params[:ruffnote_full_name])
      params.delete(:ruffnote_full_name)
    end
    super(params)
  end

  def github_full_name
    self.github ? self.github.full_name : nil
  end

  def github
    ProjectGithub.find_by(
      name: "github",
      provided_type: "Project",
      foreign_id: self.id
    )
  end

  def add_github(full_name, validate = true)
    pg = ProjectGithub.find_or_create_by(
        name: "github",
        foreign_id: self.id,
        provided_type: "Project"
    )

    if validate
      admin = User.find(self.members.find_by("is_admin = true").user_id)
      github = Github.new(oauth_token: admin.github.oauth_token)
      owner, repo_name = full_name.gsub(/[[:space:]*]/, "").split("/")
      repo = github.repos.get(owner, repo_name)
      return false unless repo
    end

    pg.full_name = full_name.gsub(/[[:space:]*]/, "")
    pg.save
  rescue Github::Error::NotFound => e
    self.errors.add(:base, "#{full_name} is not found.")
    false
  rescue ArgumentError => e
    self.errors.add(:base, "#{full_name} is invalid. Please confirm input parameters.")
    false
  rescue => e
    logger.debug "[ERROR] #{e.class} #{e.message}"
    self.errors.add(:base, "An unexpected error has occurred. Please confirm input parameters.")
    false
  end

  def ruffnote_full_name
    self.ruffnote ? self.ruffnote.full_name : nil
  end

  def ruffnote
    ProjectRuffnote.find_by(
      name: "ruffnote",
      provided_type: "Project",
      foreign_id: self.id
    )
  end

  def add_ruffnote(full_name)
    pr = ProjectRuffnote.find_or_create_by(
      name: "ruffnote",
      foreign_id: self.id,
      provided_type: "Project"
    )
    pr.full_name = full_name
    pr.save
  end

  def active?
    self.status == Project::STATUS_ACTIVE
  end

  def closed?
    self.status == Project::STATUS_CLOSED
  end

  def self.status(status)
    case status.to_i
    when Project::STATUS_ACTIVE
      self.active
    when Project::STATUS_CLOSED
      self.closed
    end
  end

  def visible?(user)
    return true if user.id == 1
    return true if self.is_public
    return true if self.members.exists?(["user_id = ?", user.id])
    false
  end

  def github_members(token)
    github = Github.new(oauth_token: token)
    owner, repo = self.github.full_name.split("/")
    cbrs = github.repos.collaborators.list(owner, repo)

    members.where(
      user_id: Authentication.where(
        provider: "github", uid: cbrs.map {|c| c.id }
      ).pluck(:user_id)
    )
  rescue => e
    logger.debug e.message
  end

  def users
    members.map { |m| m.user }
  end

  def time_entries
    Workload.where(issue_id: issues.ids)
  end

  def comments
    Comment.where(issue_id: issues.ids)
  end

  def github_issues
    IssueGithub.where(foreign_id: issues.ids)
  end

  def crowdworks_contract_id_by(user)
    crowdworks_contracts.find_by(user: user).contract_id
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  load_and_authorize_resource except: [:index, :new, :create]

  def index
    status = params[:status] || 1
    if user_signed_in?
      public_projects = Project.published.status(status).where_values.reduce(:and)
      my_projects = Project.status(status).visible(current_user).where_values.reduce(:and)
      @projects = Project.where(public_projects.or(my_projects))
    else
      @projects = Project.published.status(status)
    end

    render action: "index", status: :ok
  end

  def show
    @title = @project.name
    @issues = @project.issues.with_status
    issue_ids = @project.issues.pluck(:id)
    @comments = Comment.where(issue_id: issue_ids).order("updated_at DESC").limit(10)
    @workloads = Workload.where(issue_id: issue_ids).complete.order("updated_at DESC").limit(10)
    if user_signed_in?
      @cwcontract = @project.crowdworks_contracts.find_by(user: current_user)
    end
    @activities = PublicActivity::Activity.where(recipient: @project).order("created_at DESC").limit(10)
  end

  def new
    @project = Project.new
    authorize! :create, @project
  end

  def edit
  end

  def create
    @project = Project.new(project_params)
    authorize! :create, @project
    respond_to do |format|
      if @project.save
        m = Member.new(user: current_user, is_admin: true)
        @project.members << m
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render action: 'show', status: :created, location: @project }
      else
        format.html { render action: 'new' }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render action: 'show' }
      else
        format.html { render action: 'edit' }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  def active
    respond_to do |format|
      if @project.update(status: Project::STATUS_ACTIVE)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'show' }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  def close
    respond_to do |format|
      if @project.update(status: Project::STATUS_CLOSED)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'show' }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      res = params.require(:project).permit(:name, :description, :is_public, :parent_id, :status)
      res["github_full_name"] = params["project"]["github_full_name"].gsub(/ 　/,"") unless params["project"]["github_full_name"].blank?
      res["ruffnote_full_name"] = params["project"]["ruffnote_full_name"].gsub(/ 　/,"") unless params["project"]["ruffnote_full_name"].blank?
      return res
    end

    def require_member
      return if @project.is_public
      return redirect_to root_path, alert: "You are not project member." unless @project.member?(current_user)
    end
end

app/views/projects/_form.html.haml
= form_for(@project) do |f|
  - if @project.errors.any?
    #error_explanation
      %h2
        = pluralize(@project.errors.count, "error")
        prohibited this project from being saved:
      %ul
        - @project.errors.full_messages.each do |msg|
          %li= msg
  .form-group
    = f.label :name
    %br/
    = f.text_field :name, class: "form-control", placeholder: "Enter project name"
  .form-group
    = f.label :description
    (optional)
    %br/
    = f.text_area :description, class: "form-control"
  - if @project.persisted?
    %hr/
    - if @project.admin.github
      .form-group
        = f.label :github_full_name
        (optional)
        %br/
        = f.text_field :github_full_name, class: "form-control", placeholder: "rails/rails"
    .form-group
      = f.label :ruffnote_full_name
      (optional)
      %br/
      = f.text_field :ruffnote_full_name, class: "form-control"
  %hr/
  .radio
    %label
      = f.radio_button :is_public, "true"
      %b Public
      %br/
      %span.text-muted Anyone can see this project.
  .radio
    %label
      = f.radio_button :is_public, "false"
      %b Private
      %br/
      %span.text-muted You choose who can see to this project.
  %hr/
  .actions
    = f.submit class: "btn btn-success"

app/views/projects/_project.html.haml
%section.project
  %h2.project__title
    = link_to project.name, project
  .project__meta
    - if project.is_public
      %span.label.label-info Public
    - else
      %span.label.label-default Private
    - if project.github
      %span.label.label-default
        = project.github.full_name
  .project__description.text-muted
    = markdown(project.description)

app/views/projects/edit.html.haml
%h1 Editing project
= render 'form'
= link_to 'Back to project', @project

app/views/projects/index.html.haml
.btn-group.btn-group-sm.project__status
  = link_to "Active", projects_path(status: Project::STATUS_ACTIVE), class: "btn btn-default"
  = link_to "Closed", projects_path(status: Project::STATUS_CLOSED), class: "btn btn-default"

.row
  .project__layout.project__layout--card
    - if can?(:create, Project.new)
      .col-lg-3.col-md-3
        = link_to new_project_path, class: "project__new project__layout-unit" do
          .project__new-icon
            = fa_icon "plus"
          .project__new-text
            Add Project
    - @projects.each do |project|
      .col-lg-3.col-md-3
        .project__layout-unit
          %h3.project__name
            = link_to project.name, project
          .project__description.text-muted
            = project.description.truncate(70) if project.description
          .project__meta.text-muted
            #{project.issues.open.count} issues, #{Comment.where(issue_id: project.issues.pluck(:id)).count} comments
          .project__members
            - project.members.limit(10).each do |member|
              = link_to member.user, class: "project__member" do
                = image_tag gravatar_url(member.user.email, 45), class: "img-circle"

app/views/projects/new.html.haml
%h1 New project
= render 'form'
= link_to 'Back', projects_path

app/views/projects/show.html.haml
.row
  .col-lg-8
    %section.project
      .clearfix
        %h1.project__name
          = @project.name
          - if can? :update, @project
            .pull-right.dropdown
              = link_to "#", class: "btn btn-default", "data-toggle" => "dropdown" do
                = fa_icon "cog"
              %ul.dropdown-menu{ role: "menu", "aria-labelledby" => "dLabel" }
                - if @project.active?
                  %li
                    = link_to "Edit", edit_project_path(@project)
                  %li
                    = link_to "Manage Members", project_members_path(@project)
                  %li
                    = link_to "Close", close_project_path(@project), method: :patch
                  - if @project.github
                    %li
                      = link_to "Synchronize with the Github", project_github_imports_path(@project), method: :post
                - else
                  %li
                    = link_to "Active", active_project_path(@project), method: :patch
                %li
                  = link_to "Report", project_reports_path(@project)
                %li
                  = link_to "Export", datum_path(@project, format: :json)

      .project__description.text-muted
        = markdown(@project.description)
      .project__meta
        - if @project.is_public
          %span.label.label-info Public
        - else
          %span.label.label-default Private
        - if @project.github
          %span.label.label-default= @project.github.full_name
      - if user_signed_in? && @project.member?(current_user) && current_user.authentications.exists?(["provider = ?", "crowdworks"])
        .crowdworks-contract
          - if @cwcontract
            Crowdworks Contract ID:
            = link_to "#{@cwcontract.contract_id}", "https://crowdworks.jp/contracts/#{@cwcontract.contract_id}"
            = link_to "Edit", edit_crowdworks_contract_path(@project.crowdworks_contracts.find_by(user_id: current_user.id))
            = link_to "Destroy", @cwcontract, method: :delete, "data-confirm" => "Are you sure?"
          - else
            = link_to "Connect Crowdworks Timesheet", new_project_crowdworks_contract_path(@project)

    %section
      %h2.issues__caption
        = fa_icon "exclamation-circle"
        Issues
      .issues-index

    %section
      %h2.comments__caption
        = fa_icon "comments"
        Comments
      %ul.media-list.comment-list
        - @comments.order("id ASC").each do |comment|
          = render "comments/list_item", comment: comment

    %section
      %h2.workloads__caption
        = fa_icon "clock-o"
        WorkLoads
      %ul.media-list.workload-list
        - @workloads.each do |workload|
          = render "workloads/list_item", workload: workload

  .col-lg-4
    %section
      %h2.activities__caption
        = fa_icon "history"
        Activities
      %ul.activities-list.media-list
        = render_activities(@activities, layout: :activity)

:javascript
  (function() {
    var issues = new Timecard.Collections.Issues();
    issues.project_id = "#{@project.id}"
    issues.url = '/projects/'+#{@project.id}+'/issues'
    var workloads = new Timecard.Collections.Workloads();
    issues.fetch({
      success: function(collection) {
        var viewIssuesIndex = new Timecard.Views.IssuesIndex({
          collection: collection,
          workloads: workloads
        });
        viewIssuesIndex.render();
      }
    });
  })();