config/routes.rb
Timecard::Application.routes.draw do
  resource :dashboard, only: :show
  devise_for :users, controllers:  { omniauth_callbacks: "users/omniauth_callbacks", registrations: 'users/registrations' }
  resources :users, only: [:show] do
    resources :workloads, only: [:index] do
      get '/:year/:month/:day', on: :collection, to: 'workloads#index', as: :daily
    end
    resources :authentications
    resources :reports, only: :index
  end

  resources :members, only: [:update, :destroy]
  resources :data

  resources :comments, only: [:edit, :update, :destroy]
  resources :workloads, only: [:edit, :update, :destroy, :stop] do
    patch :stop, on: :member
  end

  resources :issues, only: [:index, :show, :edit, :update, :close, :reopen] do
    patch :close, on: :member
    patch :reopen, on: :member
    patch :postpone, on: :member
    patch :do_today, on: :member
    resources :comments, only: [:create]
    resource :workloads, only: :create
  end

  resources :projects do
    patch :active, on: :member
    patch :close, on: :member
    resources :issues, only: [:index, :new, :create]
    resources :members, only: [:index, :create] do
      collection do
        get :search
      end
    end
    resources :crowdworks_contracts, only: [:new, :create]
    resources :reports, only: :index
    resources :github_imports, only: :create
  end

  resources :crowdworks_contracts, only: [:edit, :update, :destroy]

  resources :reports, only: :index

  delete "users/disconnect/:provider", to: "users#disconnect", as: :disconnect_provider
  root :to => "home#index"
  mount API => "/"
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  before_action :authenticate_user!

  def index
    if params[:user_id]
      user_index
    elsif params[:project_id]
      project_index
    end
  end

  def user_index
    @user = User.find(params[:user_id])
    authorize! :report, @user
    @workloads = current_user.workloads
      .complete.daily
    render "user_index"
  end

  def project_index
    @project = Project.find(params[:project_id])
    @today = params[:date].present? ? Date.parse(params[:date]) : Time.zone.today
    @week = @today.beginning_of_week..@today.end_of_week
    authorize! :report, @project
    render "project_index"
  end
end

app/views/reports/index.html.haml
%h1 Reports

.row
  .col-lg-4
    .panel.panel-info
      .panel-heading
        %h2.caption
          = fa_icon "user"
          My Reports
      .panel-body
        = link_to user_reports_path(current_user) do
          = fa_icon "angle-double-right"
          Check my time entries

  .col-lg-4
    .panel.panel-info
      .panel-heading
        %h2.caption
          = fa_icon "folder"
          Project Reports
      .panel-body
        %ul
          - current_user.admin_projects.each do |project|
            %li
              = link_to project.name, project_reports_path(project)

app/views/reports/project_index.html.haml
%ol.breadcrumb
  %li
    = link_to reports_path do
      = fa_icon "angle-double-left"
      Back to top of reports

.reports__head
  %h1.caption
    = link_to @project.name, @project
    %small
      TOTAL TIME
      = @project.time_entries.formatted_total_duration
  %p
    = @project.issues.open.count
    open issues
    ,
    = @project.issues.closed.count
    closed issues
    ,
    = @project.comments.count
    comments
    ,
    = @project.members.count
    members

%ul.nav.nav-tabs{ role: "tablist" }
  %li
    = link_to project_reports_path(@project, date: 1.week.ago(@today).beginning_of_week), title: "Prev week" do
      = fa_icon "caret-left"
  - @week.each do |date|
    %li{ class: "#{@today == date ? 'active' : ''}" }
      = link_to l(date, format: :long), project_reports_path(@project, date: date), role: "tab"
  %li
    = link_to project_reports_path(@project, date: 1.week.since(@today).beginning_of_week), title: "Next week" do
      = fa_icon "caret-right"
.tab-content.time-sheet
  .tab-pane{ class: "fade active in" }
    %h2.caption
      = @today
      %small
        TOTAL TIME
        = @project.time_entries.daily(@today.to_time_in_current_zone).complete.formatted_total_duration
    %table.table.table-bordered
      %thead
        %tr
          %th User
          %th Total Duration
          %th Time Entries
      - @project.users.each do |user|
        %tr
          %td
            = image_tag gravatar_url(user.email), class: "img-circle"
            = link_to user.name, user
          %td
            = user.workloads.where(issue_id: @project.issues.ids).daily(@today.to_time_in_current_zone).complete.formatted_total_duration
          %td.time-entries
            %ul.time-entries-list
              - user.workloads.where(issue_id: @project.issues.ids).daily(@today.to_time_in_current_zone).complete.each do |workload|
                %li.time-entries-list__item
                  = workload.formatted_distance_of_time
                  %span.text-muted
                    (#{workload.formatted_duration})
                  = link_to workload.issue.subject, workload.issue

app/views/reports/user_index.html.haml
%ol.breadcrumb
  %li
    = link_to reports_path do
      = fa_icon "angle-double-left"
      Back to top of reports

%section
  %h2
    Weekly Reports
    %small
      = current_user.workloads.weekly.formatted_total_duration
  %ul.nav.nav-tabs
    - (Time.zone.today.beginning_of_week..Time.zone.today.end_of_week).each do |date|
      %li{ class: "#{date == Date.today ? 'active' : '' }" }
        = link_to l(date, format: :long), "#", class: "js-workloads-on-day-link", data: { year: date.year, month: date.month, day: date.day }
  .time-sheet
    %table.table
      %thead
        %th Project
        %th Issue
        %th Work Hours
        %th Time

      %tbody#workloads-table
        - @workloads.each do |workload|
          %tr
            %td= link_to workload.issue.project.name, workload.issue.project
            %td= link_to workload.issue.subject, workload.issue
            %td #{workload.formatted_distance_of_time}
            %td= workload.formatted_duration
        %tr
          %td Total
          %td
          %td
          %td= @workloads.formatted_total_duration